FROM node:10

RUN mkdir -p /git-repo
WORKDIR /git-repo
COPY ./package.json ./package.json  
COPY ./package-lock.json ./package-lock.json
RUN npm ci
COPY ./ ./
RUN npm run build:prod

ARG URL
ENV URL ${URL}

ARG PORT
ENV PORT ${PORT}

ARG MONGO_URL
ENV MONGO_URL ${MONGO_URL}

ARG ACCESS_TOKEN
ENV ACCESS_TOKEN ${ACCESS_TOKEN}

ARG GITHUB_CLIENT_ID
ENV GITHUB_CLIENT_ID ${GITHUB_CLIENT_ID}

ARG GITHUB_CLIENT_SECRET
ENV GITHUB_CLIENT_SECRET ${GITHUB_CLIENT_SECRET}

ARG ACCESS_GITHUB_ORGANIZATION
ENV ACCESS_GITHUB_ORGANIZATION ${ACCESS_GITHUB_ORGANIZATION}

EXPOSE 80


CMD ["npm", "run", "start"]
