const repoConfig = {
    repositories: [
        'VS-work/vs-website',
        'VS-work/ngx-bootstrap',
        'Gapminder/dollar-street-pages',
        'valor-software/dollar-street-cms-pages',
        'valor-software/dollar-street-embed-api',
        'vizabi/vizabi',
        'vizabi/vizabi-interpolators',
        'vizabi/ng2-vizabi',
        'Gapminder/ng2-tools-page',
        'vizabi/vizabi-ddfcsv-reader',
        'vizabi/vizabi-ws-reader',
        'Gapminder/ddf-validation',
        'Gapminder/gapminder-offline',
        'Gapminder/waffle-server',
        'VS-work/waffle-server-repo-service',
        'VS-work/git-csv-diff',
        'vizabi/readers-test',
        'Gapminder/ddf-time-utils',
        'VS-work/live-starter',
        'VS-work/live-starter-api',
        'MilaLys/themes-switching',
    ],
    privateRepositories: [
        'valor-software/dollar-street-consumer-api',
        'valor-software/dollar-street-cms-server',
        'valor-software/personal-crm',
        'valor-software/church-app',
    ],
    branches: [
        'master',
        'develop',
        'development',
    ],
    objectPackages: {
        express: 'express',
        lodash: 'lodash',
        tslint: 'tslint',
        typescript: 'typescript',
        angular: '@angular/common',
    },
    staticRepoData: {
        version: 'version',
        name: 'name',
        description: 'description',
    },
};

export default repoConfig;